<a href="https://colab.research.google.com/github/nurfauzinwidyantara/UTS-DATA-MINING_NUR-FAUZIN-WIDYANTARA-2304020177/blob/main/UTS_DATA_MINING_NUR_FAUZIN_177.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Library

In [1]:
import pandas as pd
import numpy as np

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Upload Data

In [2]:
uploaded = files.upload()

Saving data_training.csv to data_training.csv

In [3]:
uploaded = files.upload()

Saving data_testing.csv to data_testing.csv

Membaca Data

In [4]:
train = pd.read_csv('data_training.csv')
test = pd.read_csv('data_testing.csv')

In [5]:
train.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.3,0.740,0.08,1.7,0.094,10.0,45.0,0.99576,3.24,0.50,9.8,5,1366
1,8.1,0.575,0.22,2.1,0.077,12.0,65.0,0.99670,3.29,0.51,9.2,5,103
2,10.1,0.430,0.40,2.6,0.092,13.0,52.0,0.99834,3.22,0.64,10.0,7,942
3,12.9,0.500,0.55,2.8,0.072,7.0,24.0,1.00012,3.09,0.68,10.9,6,811
4,8.4,0.360,0.32,2.2,0.081,32.0,79.0,0.99640,3.30,0.72,11.0,6,918

In [6]:
test.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Id
0,6.8,0.61,0.04,1.5,0.057,5.0,10.0,0.99525,3.42,0.60,9.500000,222
1,6.9,0.84,0.21,4.1,0.074,16.0,65.0,0.99842,3.53,0.72,9.233333,1514
2,7.0,0.58,0.12,1.9,0.091,34.0,124.0,0.99560,3.44,0.48,10.500000,417
3,7.8,0.48,0.68,1.7,0.415,14.0,32.0,0.99656,3.09,1.06,9.100000,754
4,12.5,0.60,0.49,4.3,0.100,5.0,14.0,1.00100,3.25,0.74,11.900000,516

Melihat Ukuran Data

In [7]:
print("Ukuran Data Training :", train.shape)
print("Ukuran Data Testing :", test.shape)

Ukuran Data Training : (857, 13)
Ukuran Data Testing : (286, 12)

Cek Missing Value

In [8]:
train.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [9]:
test.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
Id                      0
dtype: int64

Memilah Fitur dan Target

In [10]:
X = train.drop(['Id', 'quality'], axis=1)
y = train['quality']

Membagi Data Latih dan Validasi

In [11]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

Normalisasi Data

In [12]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)

Membuat Model Random Forest

In [13]:
model = RandomForestClassifier(n_estimators=300, random_state=42)
model.fit(X_train_scaled, y_train)

RandomForestClassifier(n_estimators=300, random_state=42)

Evaluasi Model

In [14]:
pred_valid = model.predict(X_valid_scaled)

print("Akurasi Model =", accuracy_score(y_valid, pred_valid))
print(confusion_matrix(y_valid, pred_valid))
print(classification_report(y_valid, pred_valid))

Akurasi Model = 0.622093023255814
[[ 0  1  2  0  0]
 [ 0 44 23  0  0]
 [ 0 20 55  3  0]
 [ 0  2 11  8  0]
 [ 0  0  0  3  0]]
              precision    recall  f1-score   support

           4       0.00      0.00      0.00         3
           5       0.66      0.66      0.66        67
           6       0.60      0.71      0.65        78
           7       0.57      0.38      0.46        21
           8       0.00      0.00      0.00         3

    accuracy                           0.62       172
   macro avg       0.37      0.35      0.35       172
weighted avg       0.60      0.62      0.61       172

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Menyiapkan Data Testing

In [15]:
X_test = test.drop('Id', axis=1)
X_test_scaled = scaler.transform(X_test)

Prediksi

In [16]:
hasil_prediksi = model.predict(X_test_scaled)

Membuat CSV Hasil

In [17]:
submission = pd.DataFrame({
    'Id': test['Id'],
    'quality': hasil_prediksi
})

In [18]:
submission.to_csv('hasilprediksi_177.csv', index=False)

Unduh File Hasil

In [19]:
files.download('hasilprediksi_177.csv')